# Generated by Django 3.0.6 on 2021-06-11 06:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import model_utils.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='writeup',
        ),
        migrations.AddField(
            model_name='revision',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
