# Generated by Django 3.0.6 on 2023-02-24 17:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(6)], verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('middle_initial', models.CharField(blank=True, default='', max_length=255, verbose_name='middle initial')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='mobile number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('SOSE', 'School of Science and Engineering'), ('SOM', 'School of Management'), ('SOSS', 'School of Social Studies'), ('SOH', 'School of Humanities')], default='SOSE', max_length=4)),
                ('year_level', models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='4', max_length=2)),
                ('primary_course', models.CharField(choices=[('AB AM', 'Bachelor of Arts in Art Management'), ('AB ChnS', 'Bachelor of Arts in Chinese Studies'), ('AB COM', 'Bachelor of Arts in Communication'), ('AB DS', 'Bachelor of Arts in Development Studies'), ('AB DipIR', 'Bachelor of Arts in Diplomacy and International Relations with Specialization in East and Southeast Asian Studies'), ('AB EC-H', 'Bachelor of Arts in Economics (Honors Program)'), ('AB EC', 'Bachelor of Arts in Economics'), ('AB EU', 'Bachelor of Arts in European Studies'), ('AB HI', 'Bachelor of Arts in History'), ('AB HUM', 'Bachelor of Arts in Humanities'), ('AB IS', 'Bachelor of Arts in Interdisciplinary Studies'), ('AB LIT ENG', 'Bachelor of Arts in Literature (English)'), ('AB LIT FIL', 'Bachelor of Arts in Literature (Filipino)'), ('AB MEC', 'Bachelor of Arts in Management Economics'), ('AB PH', 'Bachelor of Arts in Philosophy'), ('AB POS', 'Bachelor of Arts in Political Science'), ('AB PSY', 'Bachelor of Arts in Psychology'), ('AB SOS', 'Bachelor of Arts in Social Sciences'), ('AB SOCIO', 'Bachelor of Arts in Sociology'), ('BFA AM', 'Bachelor of Fine Arts in Art Management'), ('BFA CW', 'Bachelor of Fine Arts in Creative Writing'), ('BFA ID', 'Bachelor of Fine Arts in Information Design'), ('BFA TA', 'Bachelor of Fine Arts in Theater Arts'), ('BS AMF', 'Bachelor of Science in Applied Mathematics with Specialization in Mathematical Finance'), ('BS AMDSc', 'Bachelor of Science in Applied Mathematics'), ('BS APS', 'Bachelor of Science in Applied Physics'), ('BS MSE', 'Bachelor of Science in Materials Science and Engineering'), ('BS BIO', 'Bachelor of Science in Biology'), ('BS CH', 'Bachelor of Science in Chemistry'), ('BS COMTECH', 'Bachelor of Science in Communications Technology Management'), ('BS CoE', 'Bachelor of Science in Computer Engineering'), ('BS CS', 'Bachelor of Science in Computer Science'), ('BS DGDD', 'Bachelor of Science in Digital Game Design and Development'), ('BS EcE', 'Bachelor of Science in Electronics and Communications Engineering'), ('BS ES', 'Bachelor of Science in Environmental Science'), ('BS HS', 'Bachelor of Science in Health Sciences'), ('BS ITE', 'Bachelor of Science in Information Technology Entrepreneurship'), ('BS LM', 'Bachelor of Science in Legal Management'), ('BS LfSci', 'Bachelor of Science in Life Sciences'), ('BS MGT', 'Bachelor of Science in Management'), ('BS MGT-H', 'Bachelor of Science in Management (Honors Program)'), ('BS ME', 'Bachelor of Science in Management Engineering'), ('BS MIS', 'Bachelor of Science in Management Information Systems'), ('BS MAC', 'Bachelor of Science in Management of Applied Chemistry'), ('BS MA', 'Bachelor of Science in Mathematics'), ('BS PS', 'Bachelor of Science in Physics'), ('BS PSY', 'Bachelor of Science in Psychology'), ('BS RENT', 'Bachelor of Science in Restaurant Entrepreneurship')], default='AB HUM', max_length=10)),
                ('secondary_course', models.CharField(blank=True, choices=[('AB AM', 'Bachelor of Arts in Art Management'), ('AB ChnS', 'Bachelor of Arts in Chinese Studies'), ('AB COM', 'Bachelor of Arts in Communication'), ('AB DS', 'Bachelor of Arts in Development Studies'), ('AB DipIR', 'Bachelor of Arts in Diplomacy and International Relations with Specialization in East and Southeast Asian Studies'), ('AB EC-H', 'Bachelor of Arts in Economics (Honors Program)'), ('AB EC', 'Bachelor of Arts in Economics'), ('AB EU', 'Bachelor of Arts in European Studies'), ('AB HI', 'Bachelor of Arts in History'), ('AB HUM', 'Bachelor of Arts in Humanities'), ('AB IS', 'Bachelor of Arts in Interdisciplinary Studies'), ('AB LIT ENG', 'Bachelor of Arts in Literature (English)'), ('AB LIT FIL', 'Bachelor of Arts in Literature (Filipino)'), ('AB MEC', 'Bachelor of Arts in Management Economics'), ('AB PH', 'Bachelor of Arts in Philosophy'), ('AB POS', 'Bachelor of Arts in Political Science'), ('AB PSY', 'Bachelor of Arts in Psychology'), ('AB SOS', 'Bachelor of Arts in Social Sciences'), ('AB SOCIO', 'Bachelor of Arts in Sociology'), ('BFA AM', 'Bachelor of Fine Arts in Art Management'), ('BFA CW', 'Bachelor of Fine Arts in Creative Writing'), ('BFA ID', 'Bachelor of Fine Arts in Information Design'), ('BFA TA', 'Bachelor of Fine Arts in Theater Arts'), ('BS AMF', 'Bachelor of Science in Applied Mathematics with Specialization in Mathematical Finance'), ('BS AMDSc', 'Bachelor of Science in Applied Mathematics'), ('BS APS', 'Bachelor of Science in Applied Physics'), ('BS MSE', 'Bachelor of Science in Materials Science and Engineering'), ('BS BIO', 'Bachelor of Science in Biology'), ('BS CH', 'Bachelor of Science in Chemistry'), ('BS COMTECH', 'Bachelor of Science in Communications Technology Management'), ('BS CoE', 'Bachelor of Science in Computer Engineering'), ('BS CS', 'Bachelor of Science in Computer Science'), ('BS DGDD', 'Bachelor of Science in Digital Game Design and Development'), ('BS EcE', 'Bachelor of Science in Electronics and Communications Engineering'), ('BS ES', 'Bachelor of Science in Environmental Science'), ('BS HS', 'Bachelor of Science in Health Sciences'), ('BS ITE', 'Bachelor of Science in Information Technology Entrepreneurship'), ('BS LM', 'Bachelor of Science in Legal Management'), ('BS LfSci', 'Bachelor of Science in Life Sciences'), ('BS MGT', 'Bachelor of Science in Management'), ('BS MGT-H', 'Bachelor of Science in Management (Honors Program)'), ('BS ME', 'Bachelor of Science in Management Engineering'), ('BS MIS', 'Bachelor of Science in Management Information Systems'), ('BS MAC', 'Bachelor of Science in Management of Applied Chemistry'), ('BS MA', 'Bachelor of Science in Mathematics'), ('BS PS', 'Bachelor of Science in Physics'), ('BS PSY', 'Bachelor of Science in Psychology'), ('BS RENT', 'Bachelor of Science in Restaurant Entrepreneurship')], default=None, max_length=10)),
                ('realschool', models.CharField(choices=[('SOSE', 'School of Science and Engineering'), ('SOM', 'School of Management'), ('SOSS', 'School of Social Studies'), ('SOH', 'School of Humanities')], default='SOSE', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
