# Generated by Django 3.0.6 on 2023-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(default='', max_length=255, verbose_name='secondary email'),
        ),
    ]
