# Generated by Django 3.0.6 on 2021-05-11 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yearbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=yearbook.models.get_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yearbook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
