# Generated by Django 3.0.6 on 2021-05-13 16:09

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_yearbook_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbook',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='empty', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='yearbook',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
    ]
