# Generated by Django 3.0.6 on 2020-11-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Revision Guidelines', max_length=255)),
                ('icon', models.URLField(blank=True, default='(Optional) Insert URL Here', max_length=255)),
                ('header', models.CharField(default='Guideline', max_length=255)),
                ('content', models.TextField(default='Insert Content Here', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
