# Generated by Django 3.0.6 on 2020-11-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidelines',
            name='user',
        ),
    ]
