# Generated by Django 3.0.6 on 2020-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0002_remove_guidelines_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='header',
            field=models.CharField(max_length=255),
        ),
    ]
