# Generated by Django 3.0.6 on 2020-11-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0003_auto_20201123_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidelines',
            name='title',
        ),
    ]
