# Generated by Django 3.0.6 on 2021-05-02 21:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0004_remove_guidelines_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidelines',
            name='header',
        ),
        migrations.AddField(
            model_name='guidelines',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
