# Generated by Django 3.0.6 on 2020-06-18 01:36

from django.db import migrations, models
import django_extensions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=models.TextField(validators=[django_extensions.validators.NoWhitespaceValidator()], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(max_length=150, validators=[django_extensions.validators.NoWhitespaceValidator()], verbose_name='title'),
        ),
    ]
