# Generated by Django 3.0.6 on 2020-08-02 09:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20200618_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
